version: '3.7'
services:
  postgres:
    image: postgres:13
    hostname: postgres
    container_name: DefiOpus
    restart: always
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - postgres:/var/lib/posstgresql/data

volumes:
  postgres:
    name: nest-db